#!/usr/bin/env python
#
#  header.py
#
#  Generate a header for the given markdown file.
#

import click

import wiki


@click.command()
@click.argument("filename")
def header(filename):
    h = wiki.gen_header(filename)
    print(h)


if __name__ == "__main__":
    header()
